<a href="https://colab.research.google.com/github/alinelima1909/Atividade-notas-dos-alunos_desafio1_python-colab/blob/main/01_preparacao_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 01 – Preparação dos Dados

## Contexto
Este notebook tem como objetivo realizar a preparação dos dados que serão utilizados
nas análises de internações, reincidência, evasão de tratamento e perfil do paciente
em um projeto de Ciência de Dados aplicado à Saúde Mental.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Mental Health Dataset.csv')

In [ ]:
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [ ]:
df.shape

(292364, 17)

Informações Gerais

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                292364 non-null  object
 1   Gender                   292364 non-null  object
 2   Country                  292364 non-null  object
 3   Occupation               292364 non-null  object
 4   self_employed            287162 non-null  object
 5   family_history           292364 non-null  object
 6   treatment                292364 non-null  object
 7   Days_Indoors             292364 non-null  object
 8   Growing_Stress           292364 non-null  object
 9   Changes_Habits           292364 non-null  object
 10  Mental_Health_History    292364 non-null  object
 11  Mood_Swings              292364 non-null  object
 12  Coping_Struggles         292364 non-null  object
 13  Work_Interest            292364 non-null  object
 14  Social_Weakness          292364 non-null  object
 15  mental_health_interview  292364 non-null  object
 16  care_options             292364 non-null  object
dtypes: object(17)
memory usage: 37.9+ MB

Estatisticas Descritivas

In [ ]:
df.describe()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,292364,292364,292364,292364,287162,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364
unique,580,2,35,5,2,2,2,5,3,3,3,3,2,3,3,3,3
top,8/27/2014 11:43,Male,United States,Housewife,No,No,Yes,1-14 days,Maybe,Yes,No,Medium,No,No,Maybe,No,No
freq,2384,239850,171308,66351,257994,176832,147606,63548,99985,109523,104018,101064,154328,105843,103393,232166,118886

Estatisticas Desritivas Categóricas

In [ ]:
df.describe(include='object')

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,292364,292364,292364,292364,287162,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364
unique,580,2,35,5,2,2,2,5,3,3,3,3,2,3,3,3,3
top,8/27/2014 11:43,Male,United States,Housewife,No,No,Yes,1-14 days,Maybe,Yes,No,Medium,No,No,Maybe,No,No
freq,2384,239850,171308,66351,257994,176832,147606,63548,99985,109523,104018,101064,154328,105843,103393,232166,118886

In [ ]:
df.isnull().sum().sort_values(ascending=False)

self_employed              5202
Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

Percentual dos Faltantes

In [ ]:
(df.isnull().mean() * 100).sort_values(ascending=False)

self_employed              1.779289
Timestamp                  0.000000
Gender                     0.000000
Country                    0.000000
Occupation                 0.000000
family_history             0.000000
treatment                  0.000000
Days_Indoors               0.000000
Growing_Stress             0.000000
Changes_Habits             0.000000
Mental_Health_History      0.000000
Mood_Swings                0.000000
Coping_Struggles           0.000000
Work_Interest              0.000000
Social_Weakness            0.000000
mental_health_interview    0.000000
care_options               0.000000
dtype: float64

Padronização de nomes das colunas

In [ ]:
df.columns = (
    df.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('-', '_')
)

In [ ]:
df.columns

Index(['timestamp', 'gender', 'country', 'occupation', 'self_employed',
       'family_history', 'treatment', 'days_indoors', 'growing_stress',
       'changes_habits', 'mental_health_history', 'mood_swings',
       'coping_struggles', 'work_interest', 'social_weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

Tipos unicos de colunas para inspecção

In [ ]:
for col in df.columns:
    print(f'\nColuna: {col}')
    print(df[col].unique()[:10])

Coluna: timestamp
['8/27/2014 11:29' '8/27/2014 11:31' '8/27/2014 11:32' '8/27/2014 11:37'
 '8/27/2014 11:43' '8/27/2014 11:49' '8/27/2014 11:51' '8/27/2014 11:52'
 '8/27/2014 12:18' '8/27/2014 12:37']

Coluna: gender
['Female' 'Male']

Coluna: country
['United States' 'Poland' 'Australia' 'Canada' 'United Kingdom'
 'South Africa' 'Sweden' 'New Zealand' 'Netherlands' 'India']

Coluna: occupation
['Corporate' 'Student' 'Business' 'Housewife' 'Others']

Coluna: self_employed
[nan 'No' 'Yes']

Coluna: family_history
['No' 'Yes']

Coluna: treatment
['Yes' 'No']

Coluna: days_indoors
['1-14 days' 'Go out Every day' 'More than 2 months' '15-30 days'
 '31-60 days']

Coluna: growing_stress
['Yes' 'No' 'Maybe']

Coluna: changes_habits
['No' 'Yes' 'Maybe']

Coluna: mental_health_history
['Yes' 'No' 'Maybe']

Coluna: mood_swings
['Medium' 'Low' 'High']

Coluna: coping_struggles
['No' 'Yes']

Coluna: work_interest
['No' 'Maybe' 'Yes']

Coluna: social_weakness
['Yes' 'No' 'Maybe']

Coluna: mental_health_interview
['No' 'Maybe' 'Yes']

Coluna: care_options
['Not sure' 'No' 'Yes']

Salvando a base de dados

In [ ]:
df.to_csv('/content/mental_health_dataset_preparado.csv', index=False)